version: '3.8'

services:
  image-generator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Optional: mount output directory to save generated images to host
      - ./output:/app/output
    environment:
      - DENO_DIR=/deno-dir
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

